default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: nikki
  password: password123

development:
  <<: *default
  database: currency_development

test:
  <<: *default
  database: currency_test